/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Persistent__1 = IDL.Variant({
  'other' : IDL.Null,
  'kitFee' : IDL.Null,
  'matchFee' : IDL.Null,
});
export const Persistent = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'category' : Persistent__1,
  'playerMobile' : IDL.Text,
  'amount' : IDL.Nat,
  'matchDate' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Persistent__3 = IDL.Record({
  'targetScore' : IDL.Opt(IDL.Nat),
  'overs' : IDL.Nat,
  'battingTeam' : IDL.Text,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
});
export const Persistent__2 = IDL.Record({
  'oversPerInning' : IDL.Nat,
  'isLive' : IDL.Bool,
  'matchFormat' : IDL.Text,
  'inning1' : Persistent__3,
  'inning2' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func([Persistent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearLiveScore' : IDL.Func([IDL.Text], [], []),
  'deletePayment' : IDL.Func([IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinanceSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCollected' : IDL.Nat,
          'totalPending' : IDL.Nat,
          'perPlayerSummary' : IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Record({ 'pending' : IDL.Nat, 'collected' : IDL.Nat }),
            )
          ),
        }),
      ],
      ['query'],
    ),
  'getLiveScore' : IDL.Func([IDL.Text], [IDL.Opt(Persistent__2)], ['query']),
  'getPayments' : IDL.Func([], [IDL.Vec(Persistent)], ['query']),
  'getPaymentsByPlayer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Persistent)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setLiveScore' : IDL.Func([IDL.Text, Persistent__2], [], []),
  'updatePayment' : IDL.Func([IDL.Text, Persistent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Persistent__1 = IDL.Variant({
    'other' : IDL.Null,
    'kitFee' : IDL.Null,
    'matchFee' : IDL.Null,
  });
  const Persistent = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'category' : Persistent__1,
    'playerMobile' : IDL.Text,
    'amount' : IDL.Nat,
    'matchDate' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Persistent__3 = IDL.Record({
    'targetScore' : IDL.Opt(IDL.Nat),
    'overs' : IDL.Nat,
    'battingTeam' : IDL.Text,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
  });
  const Persistent__2 = IDL.Record({
    'oversPerInning' : IDL.Nat,
    'isLive' : IDL.Bool,
    'matchFormat' : IDL.Text,
    'inning1' : Persistent__3,
    'inning2' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func([Persistent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearLiveScore' : IDL.Func([IDL.Text], [], []),
    'deletePayment' : IDL.Func([IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinanceSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCollected' : IDL.Nat,
            'totalPending' : IDL.Nat,
            'perPlayerSummary' : IDL.Vec(
              IDL.Tuple(
                IDL.Text,
                IDL.Record({ 'pending' : IDL.Nat, 'collected' : IDL.Nat }),
              )
            ),
          }),
        ],
        ['query'],
      ),
    'getLiveScore' : IDL.Func([IDL.Text], [IDL.Opt(Persistent__2)], ['query']),
    'getPayments' : IDL.Func([], [IDL.Vec(Persistent)], ['query']),
    'getPaymentsByPlayer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Persistent)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setLiveScore' : IDL.Func([IDL.Text, Persistent__2], [], []),
    'updatePayment' : IDL.Func([IDL.Text, Persistent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };