/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Persistent {
  'id' : string,
  'date' : string,
  'description' : string,
  'isPaid' : boolean,
  'category' : Persistent__1,
  'playerMobile' : string,
  'amount' : bigint,
  'matchDate' : [] | [string],
}
export type Persistent__1 = { 'other' : null } |
  { 'kitFee' : null } |
  { 'matchFee' : null };
export interface Persistent__2 {
  'oversPerInning' : bigint,
  'isLive' : boolean,
  'matchFormat' : string,
  'inning1' : Persistent__3,
  'inning2' : Array<[string, bigint]>,
}
export interface Persistent__3 {
  'targetScore' : [] | [bigint],
  'overs' : bigint,
  'battingTeam' : string,
  'runs' : bigint,
  'wickets' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<[Persistent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearLiveScore' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinanceSummary' : ActorMethod<
    [],
    {
      'totalCollected' : bigint,
      'totalPending' : bigint,
      'perPlayerSummary' : Array<
        [string, { 'pending' : bigint, 'collected' : bigint }]
      >,
    }
  >,
  'getLiveScore' : ActorMethod<[string], [] | [Persistent__2]>,
  'getPayments' : ActorMethod<[], Array<Persistent>>,
  'getPaymentsByPlayer' : ActorMethod<[string], Array<Persistent>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setLiveScore' : ActorMethod<[string, Persistent__2], undefined>,
  'updatePayment' : ActorMethod<[string, Persistent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];