/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Persistent {
    id: string;
    date: string;
    description: string;
    isPaid: boolean;
    category: Persistent__1;
    playerMobile: string;
    amount: bigint;
    matchDate?: string;
}
export interface Persistent__2 {
    oversPerInning: bigint;
    isLive: boolean;
    matchFormat: string;
    inning1: Persistent__3;
    inning2: Array<[string, bigint]>;
}
export interface Persistent__3 {
    targetScore?: bigint;
    overs: bigint;
    battingTeam: string;
    runs: bigint;
    wickets: bigint;
}
export enum Persistent__1 {
    other = "other",
    kitFee = "kitFee",
    matchFee = "matchFee"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPayment(_payment: Persistent): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearLiveScore(_matchDate: string): Promise<void>;
    deletePayment(_id: string): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getFinanceSummary(): Promise<{
        totalCollected: bigint;
        totalPending: bigint;
        perPlayerSummary: Array<[string, {
                pending: bigint;
                collected: bigint;
            }]>;
    }>;
    getLiveScore(_matchDate: string): Promise<Persistent__2 | null>;
    getPayments(): Promise<Array<Persistent>>;
    getPaymentsByPlayer(_mobileNumber: string): Promise<Array<Persistent>>;
    isCallerAdmin(): Promise<boolean>;
    setLiveScore(_matchDate: string, _liveScore: Persistent__2): Promise<void>;
    updatePayment(_id: string, _updatedPayment: Persistent): Promise<void>;
}
import type { Persistent as _Persistent, Persistent__1 as _Persistent__1, Persistent__2 as _Persistent__2, Persistent__3 as _Persistent__3, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPayment(arg0: Persistent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Persistent_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Persistent_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearLiveScore(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLiveScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLiveScore(arg0);
            return result;
        }
    }
    async deletePayment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinanceSummary(): Promise<{
        totalCollected: bigint;
        totalPending: bigint;
        perPlayerSummary: Array<[string, {
                pending: bigint;
                collected: bigint;
            }]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinanceSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinanceSummary();
            return result;
        }
    }
    async getLiveScore(arg0: string): Promise<Persistent__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveScore(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveScore(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(): Promise<Array<Persistent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentsByPlayer(arg0: string): Promise<Array<Persistent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentsByPlayer(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentsByPlayer(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async setLiveScore(arg0: string, arg1: Persistent__2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLiveScore(arg0, to_candid_Persistent__2_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLiveScore(arg0, to_candid_Persistent__2_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePayment(arg0: string, arg1: Persistent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, to_candid_Persistent_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, to_candid_Persistent_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Persistent__1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Persistent__1): Persistent__1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Persistent__2_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Persistent__2): Persistent__2 {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Persistent__3_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Persistent__3): Persistent__3 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Persistent_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Persistent): Persistent {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Persistent__2]): Persistent__2 | null {
    return value.length === 0 ? null : from_candid_Persistent__2_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oversPerInning: bigint;
    isLive: boolean;
    matchFormat: string;
    inning1: _Persistent__3;
    inning2: Array<[string, bigint]>;
}): {
    oversPerInning: bigint;
    isLive: boolean;
    matchFormat: string;
    inning1: Persistent__3;
    inning2: Array<[string, bigint]>;
} {
    return {
        oversPerInning: value.oversPerInning,
        isLive: value.isLive,
        matchFormat: value.matchFormat,
        inning1: from_candid_Persistent__3_n12(_uploadFile, _downloadFile, value.inning1),
        inning2: value.inning2
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetScore: [] | [bigint];
    overs: bigint;
    battingTeam: string;
    runs: bigint;
    wickets: bigint;
}): {
    targetScore?: bigint;
    overs: bigint;
    battingTeam: string;
    runs: bigint;
    wickets: bigint;
} {
    return {
        targetScore: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.targetScore)),
        overs: value.overs,
        battingTeam: value.battingTeam,
        runs: value.runs,
        wickets: value.wickets
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    description: string;
    isPaid: boolean;
    category: _Persistent__1;
    playerMobile: string;
    amount: bigint;
    matchDate: [] | [string];
}): {
    id: string;
    date: string;
    description: string;
    isPaid: boolean;
    category: Persistent__1;
    playerMobile: string;
    amount: bigint;
    matchDate?: string;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        isPaid: value.isPaid,
        category: from_candid_Persistent__1_n18(_uploadFile, _downloadFile, value.category),
        playerMobile: value.playerMobile,
        amount: value.amount,
        matchDate: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.matchDate))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    kitFee: null;
} | {
    matchFee: null;
}): Persistent__1 {
    return "other" in value ? Persistent__1.other : "kitFee" in value ? Persistent__1.kitFee : "matchFee" in value ? Persistent__1.matchFee : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Persistent>): Array<Persistent> {
    return value.map((x)=>from_candid_Persistent_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Persistent__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Persistent__1): _Persistent__1 {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Persistent__2_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Persistent__2): _Persistent__2 {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Persistent__3_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Persistent__3): _Persistent__3 {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Persistent_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Persistent): _Persistent {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: string;
    description: string;
    isPaid: boolean;
    category: Persistent__1;
    playerMobile: string;
    amount: bigint;
    matchDate?: string;
}): {
    id: string;
    date: string;
    description: string;
    isPaid: boolean;
    category: _Persistent__1;
    playerMobile: string;
    amount: bigint;
    matchDate: [] | [string];
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        isPaid: value.isPaid,
        category: to_candid_Persistent__1_n3(_uploadFile, _downloadFile, value.category),
        playerMobile: value.playerMobile,
        amount: value.amount,
        matchDate: value.matchDate ? candid_some(value.matchDate) : candid_none()
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oversPerInning: bigint;
    isLive: boolean;
    matchFormat: string;
    inning1: Persistent__3;
    inning2: Array<[string, bigint]>;
}): {
    oversPerInning: bigint;
    isLive: boolean;
    matchFormat: string;
    inning1: _Persistent__3;
    inning2: Array<[string, bigint]>;
} {
    return {
        oversPerInning: value.oversPerInning,
        isLive: value.isLive,
        matchFormat: value.matchFormat,
        inning1: to_candid_Persistent__3_n23(_uploadFile, _downloadFile, value.inning1),
        inning2: value.inning2
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    targetScore?: bigint;
    overs: bigint;
    battingTeam: string;
    runs: bigint;
    wickets: bigint;
}): {
    targetScore: [] | [bigint];
    overs: bigint;
    battingTeam: string;
    runs: bigint;
    wickets: bigint;
} {
    return {
        targetScore: value.targetScore ? candid_some(value.targetScore) : candid_none(),
        overs: value.overs,
        battingTeam: value.battingTeam,
        runs: value.runs,
        wickets: value.wickets
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Persistent__1): {
    other: null;
} | {
    kitFee: null;
} | {
    matchFee: null;
} {
    return value == Persistent__1.other ? {
        other: null
    } : value == Persistent__1.kitFee ? {
        kitFee: null
    } : value == Persistent__1.matchFee ? {
        matchFee: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
